# A list of Warp Route token configs
# These configs will be merged with the warp routes in the configured registry
# The input here is typically the output of the Hyperlane CLI warp deploy command
---
tokens:
  - chainName: pruvtest
    standard: EvmHypCollateral
    decimals: 6
    symbol: TUSDT
    name: Test Tether USD
    addressOrDenom: "0xAd8fBFC529E5587362db9A283CB8206049Ff296f"
    collateralAddressOrDenom: "0x4Fc9442273BDbCc246248d701F32E40Cc43C304c"
    connections:
      - token: ethereum|arbitrumsepolia|0xd6fbCDD11F63280B2C748500346747130E024569
      - token: ethereum|sepolia|0x787e29122fA320A903257347d6a6b1430F0AD511
  - chainName: arbitrumsepolia
    standard: EvmHypCollateral
    decimals: 18
    symbol: TUSDT
    name: Test Tether USD
    addressOrDenom: "0xd6fbCDD11F63280B2C748500346747130E024569"
    collateralAddressOrDenom: "0xDBC700677c96cc95A0BaadE4950C9A1646e8b12A"
    connections:
      - token: ethereum|pruvtest|0xAd8fBFC529E5587362db9A283CB8206049Ff296f
      - token: ethereum|sepolia|0x787e29122fA320A903257347d6a6b1430F0AD511
  - chainName: sepolia
    standard: EvmHypCollateral
    decimals: 12
    symbol: TUSDT
    name: Test Tether USD
    addressOrDenom: "0x787e29122fA320A903257347d6a6b1430F0AD511"
    collateralAddressOrDenom: "0x7e61860bf47656ba7C51713547a3faB6291aEB7d"
    connections:
      - token: ethereum|pruvtest|0xAd8fBFC529E5587362db9A283CB8206049Ff296f
      - token: ethereum|arbitrumsepolia|0xd6fbCDD11F63280B2C748500346747130E024569
options: {}
